<?php
/**
 * File to handle the AWS S3 support as directory listing.
 *
 * Hints:
 * - Public bucket URLs are created like this: https://console.aws.amazon.com/s3/buckets/BucketName/
 * - Public file URLs are created like this: https://BucketName.s3.Region.amazonaws.com/filename.png
 * - Public file URLs are not generated by S3 API, they must be custom created
 *
 * @package external-files-in-media-library
 */

namespace ExternalFilesInMediaLibrary\Services;

// prevent direct access.
defined( 'ABSPATH' ) || exit;

use Aws\EndpointV2\EndpointDefinitionProvider;
use Aws\S3\Exception\S3Exception;
use Aws\S3\S3Client;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Fields\Number;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Fields\Password;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Fields\Select;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Fields\Text;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Fields\TextInfo;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Page;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Section;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Settings;
use ExternalFilesInMediaLibrary\Dependencies\easySettingsForWordPress\Tab;
use ExternalFilesInMediaLibrary\ExternalFiles\Export_Base;
use ExternalFilesInMediaLibrary\ExternalFiles\ImportDialog;
use easyDirectoryListingForWordPress\Crypt;
use ExternalFilesInMediaLibrary\ExternalFiles\Protocol_Base;
use ExternalFilesInMediaLibrary\Plugin\Helper;
use ExternalFilesInMediaLibrary\Plugin\Languages;
use ExternalFilesInMediaLibrary\Plugin\Log;
use ExternalFilesInMediaLibrary\Services\S3\Export;
use WP_Error;
use WP_User;

/**
 * Object to handle support for AWS S3-based directory listing.
 */
class S3 extends Service_Base implements Service {
	/**
	 * The object name.
	 *
	 * @var string
	 */
	protected string $name = 's3';

	/**
	 * The public label.
	 *
	 * @var string
	 */
	protected string $label = 'AWS S3';

	/**
	 * Slug of settings tab.
	 *
	 * @var string
	 */
	protected string $settings_sub_tab = 'eml_s3';

	/**
	 * Instance of actual object.
	 *
	 * @var ?S3
	 */
	private static ?S3 $instance = null;

	/**
	 * Constructor, not used as this a Singleton object.
	 */
	private function __construct() {}

	/**
	 * Prevent cloning of this object.
	 *
	 * @return void
	 */
	private function __clone() {}

	/**
	 * Return instance of this object as singleton.
	 *
	 * @return S3
	 */
	public static function get_instance(): S3 {
		if ( is_null( self::$instance ) ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	/**
	 * Run during activation of the plugin.
	 *
	 * @return void
	 */
	public function activation(): void {}

	/**
	 * Initialize this object.
	 *
	 * @return void
	 */
	public function init(): void {
		// use parent initialization.
		parent::init();

		// add settings.
		add_action( 'init', array( $this, 'init_aws_s3' ), 30 );

		// bail if user has no capability for this service.
		if ( ! current_user_can( 'efml_cap_' . $this->get_name() ) ) {
			return;
		}

		// set title.
		$this->title = __( 'Choose file(s) from your AWS S3 server', 'external-files-in-media-library' );

		// use our own hooks.
		add_filter( 'efml_service_s3_hide_file', array( $this, 'prevent_not_allowed_files' ), 10, 3 );
		add_filter( 'efml_protocols', array( $this, 'add_protocol' ) );
		add_filter( 'efml_directory_listing', array( $this, 'prepare_tree_building' ), 10, 3 );
		add_filter( 'efml_http_header_args', array( $this, 'remove_authorization_header' ), 10, 2 );
		add_filter( 'efml_aws_s3_query_params', array( $this, 'change_file_query' ) );
		add_filter( 'efml_http_check_content_type', array( $this, 'allow_content_type' ), 10, 2 );
		add_filter( 'efml_files_check_content_type', array( $this, 'allow_content_type' ), 10, 2 );
		add_filter( 'efml_external_file_infos', array( $this, 'set_real_mime_type' ), 10, 2 );

		// use hooks.
		add_action( 'show_user_profile', array( $this, 'add_user_settings' ) );
	}

	/**
	 * Return the directory listing structure.
	 *
	 * @param string $directory The requested directory.
	 *
	 * @return array<int|string,mixed>
	 */
	public function get_directory_listing( string $directory ): array {
		// get the S3Client.
		$s3 = $this->get_s3_client();

		// get list of directories and files in given bucket.
		try {
			// create the query to load the list of files.
			$query = array(
				'Bucket' => $this->get_bucket_name(),
			);

			/**
			 * Filter the query for files in AWS S3.
			 *
			 * @since 5.0.0 Available since 5.0.0.
			 * @param array $query The query.
			 * @param string $directory The URL.
			 */
			$query = apply_filters( 'efml_aws_s3_query_params', $query, $directory );

			// try to load the requested bucket.
			$result = $s3->listObjectsV2( $query );

			/**
			 * Get list of files.
			 *
			 * This will be all files in the complete bucket incl. subdirectories.
			 */
			$files = $result['Contents'];

			// bail if no data returned.
			if ( ! is_array( $files ) || empty( $files ) ) {
				// create error object.
				$error = new WP_Error();
				$error->add( 'efml_service_s3', __( 'No files returned from AWS S3.', 'external-files-in-media-library' ) );

				// add it to the list.
				$this->add_error( $error );

				// do nothing more.
				return array();
			}

			// collect the content of this directory.
			$listing = array(
				'title' => $this->get_directory(),
				'files' => array(),
				'dirs'  => array(),
			);

			// collect list of folders.
			$folders = array();

			// add each file to the list.
			foreach ( $files as $file ) {
				$false = false;
				/**
				 * Filter whether given AWS S3 file should be hidden.
				 *
				 * @since 5.0.0 Available since 5.0.0.
				 *
				 * @param bool $false True if it should be hidden.
				 * @param array<string,mixed> $file The array with the file data.
				 * @param string $directory The requested directory.
				 *
				 * @noinspection PhpConditionAlreadyCheckedInspection
				 */
				if ( apply_filters( 'efml_service_s3_hide_file', $false, $file, $directory ) ) {
					continue;
				}

				// get directory-data for this file and add file in the given directories.
				$parts = explode( '/', $file['Key'] );

				// collect the entry.
				$entry = array(
					'title' => basename( $file['Key'] ),
				);

				// if array contains more than 1 entry this file is in a directory.
				if ( end( $parts ) ) {
					// get content type of this file.
					$mime_type = wp_check_filetype( basename( $file['Key'] ) );

					// bail if file type is not allowed.
					if ( empty( $mime_type['type'] ) ) {
						continue;
					}

					// add settings for entry.
					$entry['s3_key']        = $file['Key'];
					$entry['file']          = $this->get_public_url_of_file( $file['Key'] );
					$entry['filesize']      = absint( $file['Size'] );
					$entry['mime-type']     = $mime_type['type'];
					$entry['icon']          = '<span class="dashicons dashicons-media-default" data-type="' . esc_attr( $mime_type['type'] ) . '"></span>';
					$entry['last-modified'] = Helper::get_format_date_time( gmdate( 'Y-m-d H:i:s', absint( $file['LastModified']->format( 'U' ) ) ) );
					$entry['preview']       = '';
				}

				if ( count( $parts ) > 1 ) {
					$the_keys = array_keys( $parts );
					$last_key = end( $the_keys );
					$last_dir = '';
					$dir_path = '';

					// loop through all parent folders, add the directory if it does not exist in the list
					// and add the file to each of them.
					foreach ( $parts as $key => $dir ) {
						// bail if dir is empty.
						if ( empty( $dir ) ) {
							continue;
						}

						// bail for last entry (which is a file).
						if ( $key === $last_key ) {
							// add the file to the last iterated directory.
							$folders[ $last_dir ]['files'][] = $entry;
							continue;
						}

						// add the path.
						$dir_path .= trailingslashit( $dir );

						// create the full path.
						$index = $this->get_directory() . $dir_path;

						// add the directory if it does not exist atm in the main folder list.
						if ( ! isset( $folders[ $index ] ) ) {
							// add the directory to the list.
							$folders[ $index ] = array(
								'title' => $dir,
								'files' => array(),
								'dirs'  => array(),
							);
						}

						// add the directory if it does not exist atm in the main folder list.
						if ( ! empty( $last_dir ) && ! isset( $folders[ $last_dir ]['dirs'][ $index ] ) ) {
							// add the directory to the list.
							$folders[ $last_dir ]['dirs'][ $index ] = array(
								'title' => $dir,
								'files' => array(),
								'dirs'  => array(),
							);
						}

						// mark this dir as last dir for file path.
						$last_dir = $index;
					}
				} else {
					// simply add the entry to the list if no directory data exist.
					$listing['files'][] = $entry;
				}
			}

			// return the resulting file list.
			return array_merge( array( 'completed' => true ), array( $this->get_directory() => $listing ), $folders );
		} catch ( S3Exception $e ) {
			// create error object.
			$error = new WP_Error();
			/* translators: %1$d will be replaced by an HTTP-status code like 403. */
			$error->add( 'efml_service_s3', sprintf( __( 'Credentials and/or bucket are not valid. AWS S3 returns with HTTP-Status %1$d!', 'external-files-in-media-library' ), $e->getStatusCode() ) );

			// add it to the list.
			$this->add_error( $error );

			return array();
		}
	}

	/**
	 * Return the actions.
	 *
	 * @return array<int,array<string,string>>
	 */
	public function get_actions(): array {
		// get list of allowed mime types.
		$mimetypes = implode( ',', Helper::get_allowed_mime_types() );

		return array(
			array(
				'action' => 'efml_get_import_dialog( { "service": "' . $this->get_name() . '", "urls": file.file, "fields": config.fields, "term": term } );',
				'label'  => __( 'Import', 'external-files-in-media-library' ),
				'show'   => 'let mimetypes = "' . $mimetypes . '";mimetypes.includes( file["mime-type"] )',
				'hint'   => '<span class="dashicons dashicons-editor-help" title="' . esc_attr__( 'File-type is not supported', 'external-files-in-media-library' ) . '"></span>',
			),
		);
	}

	/**
	 * Return global actions.
	 *
	 * @return array<int,array<string,string>>
	 */
	protected function get_global_actions(): array {
		return array_merge(
			parent::get_global_actions(),
			array(
				array(
					'action' => 'location.href="https://console.aws.amazon.com/s3/buckets/";',
					'label'  => __( 'Go to AWS S3 Bucket', 'external-files-in-media-library' ),
				),
				array(
					'action' => 'efml_get_import_dialog( { "service": "' . $this->get_name() . '", "urls": "' . $this->get_url_mark( $this->get_bucket_name() ) . '" + actualDirectoryPath, "fields": config.fields, "term": config.term } );',
					'label'  => __( 'Import active directory', 'external-files-in-media-library' ),
				),
				array(
					'action' => 'efml_save_as_directory( "' . $this->get_name() . '", "' . $this->get_url_mark( $this->get_bucket_name() ) . '" + actualDirectoryPath, config.fields, config.term );',
					'label'  => __( 'Save active directory as your external source', 'external-files-in-media-library' ),
				),
			)
		);
	}

	/**
	 * Check if login with given credentials is valid.
	 *
	 * @param string $directory The directory to check.
	 *
	 * @return bool
	 */
	public function do_login( string $directory ): bool {
		// bail if credentials are missing.
		if ( empty( $this->get_fields() ) ) {
			// create error object.
			$error = new WP_Error();
			$error->add( 'efml_service_s3', __( 'No credentials set for this AWS S3 connection!', 'external-files-in-media-library' ) );

			// add it to the list.
			$this->add_error( $error );

			// return false to login check.
			return false;
		}

		// get AWS S3 client to check if credentials are ok.
		$s3 = $this->get_s3_client();
		try {
			// try to load the requested bucket.
			$s3->listObjectsV2( array( 'Bucket' => $this->get_bucket_name() ) );

			// return true if it could be loaded.
			return true;
		} catch ( S3Exception $e ) {
			// create error object.
			$error = new WP_Error();
			/* translators: %1$d will be replaced by an HTTP-status code like 403. */
			$error->add( 'efml_service_s3', sprintf( __( 'Credentials and/or bucket are not valid. AWS S3 returns with HTTP-Status %1$d!', 'external-files-in-media-library' ), $e->getStatusCode() ) );

			// add it to the list.
			$this->add_error( $error );

			// add log entry.
			/* translators: %1$d will be replaced by an HTTP-status (like 301). */
			Log::get_instance()->create( sprintf( __( 'Credentials and/or bucket are not valid. AWS S3 returns with HTTP-Status %1$d! Error:', 'external-files-in-media-library' ), $e->getStatusCode() ) . ' <code>' . $e->getMessage() . '</code>', '', 'error' );

			// return false to prevent any further actions.
			return false;
		}
	}

	/**
	 * Return the S3Client object with given credentials.
	 *
	 * @return S3Client
	 */
	public function get_s3_client(): S3Client {
		// get the fields.
		$fields = $this->get_fields();

		// create and return the AWS S3 client object.
		return new S3Client(
			array(
				'version'     => 'latest',
				'region'      => $this->get_region(),
				'credentials' => array(
					'key'    => $fields['access_key']['value'],
					'secret' => $fields['secret']['value'],
				),
			)
		);
	}

	/**
	 * Return region from settings.
	 *
	 * @return string
	 */
	public function get_region(): string {
		// get the fields.
		$fields = $this->get_fields();

		// return the region from fields.
		if ( ! empty( $fields['region']['value'] ) ) {
			return $fields['region']['value'];
		}

		// get from global setting, if enabled.
		if ( in_array( get_option( 'eml_' . $this->get_name() . '_credentials_vault' ), array( 'global', 'manually' ), true ) ) {
			return get_option( 'eml_s3_region', 'eu-central-1' );
		}

		// get from user setting, if enabled.
		if ( 'user' === get_option( 'eml_' . $this->get_name() . '_credentials_vault' ) ) {
			// get current user.
			$user = $this->get_user();

			// bail if user is not available.
			if ( ! $user instanceof WP_User ) { // @phpstan-ignore instanceof.alwaysTrue
				return '';
			}

			// get the setting.
			$region = get_user_meta( $user->ID, 'efml_s3_region', true );

			// bail if value is not a string.
			if ( ! is_string( $region ) ) {
				return '';
			}

			// return the region from settings.
			return Crypt::get_instance()->decrypt( $region );
		}

		// return empty string.
		return '';
	}

	/**
	 * Enable WP CLI for AWS S3 tasks.
	 *
	 * @return void
	 */
	public function cli(): void {}

	/**
	 * Return the directory to use.
	 *
	 * @return string
	 */
	public function get_directory(): string {
		// bail if no bucket is set.
		if ( empty( $this->get_bucket_name() ) ) {
			return '/';
		}

		// return the URL with bucket.
		return $this->get_url_mark( $this->get_bucket_name() );
	}

	/**
	 * Prevent visibility of not allowed mime types.
	 *
	 * @param bool                $result True if it should be hidden.
	 * @param array<string,mixed> $file The array with the file data.
	 * @param string              $url The requested directory.
	 *
	 * @return bool
	 * @noinspection PhpUnusedParameterInspection
	 */
	public function prevent_not_allowed_files( bool $result, array $file, string $url ): bool {
		// bail if setting is disabled.
		if ( 1 !== absint( get_option( 'eml_directory_listing_hide_not_supported_file_types' ) ) ) {
			return $result;
		}

		// get content type of this file.
		$mime_type = wp_check_filetype( basename( $file['Key'] ) );

		// return whether this file type is allowed (false) or not (true).
		return ! in_array( $mime_type['type'], Helper::get_allowed_mime_types(), true );
	}

	/**
	 * Add our own protocol.
	 *
	 * @param array<string> $protocols List of protocols.
	 *
	 * @return array<string>
	 */
	public function add_protocol( array $protocols ): array {
		// add the AWS S3 protocol before the HTTPS-protocol and return resulting list of protocols.
		array_unshift( $protocols, 'ExternalFilesInMediaLibrary\Services\S3\Protocol' );

		// return the resulting list.
		return $protocols;
	}

	/**
	 * Add settings for AWS S3 support.
	 *
	 * @return void
	 */
	public function init_aws_s3(): void {
		// bail if user has no capability for this service.
		if ( ! Helper::is_cli() && ! current_user_can( 'efml_cap_' . $this->get_name() ) ) {
			return;
		}

		// get the settings object.
		$settings_obj = Settings::get_instance();

		// get the settings page.
		$settings_page = $settings_obj->get_page( \ExternalFilesInMediaLibrary\Plugin\Settings::get_instance()->get_menu_slug() );

		// bail if page does not exist.
		if ( ! $settings_page instanceof Page ) {
			return;
		}

		// get tab for services.
		$services_tab = $settings_page->get_tab( $this->get_settings_tab_slug() );

		// bail if tab does not exist.
		if ( ! $services_tab instanceof Tab ) {
			return;
		}

		// add new tab for settings.
		$tab = $services_tab->get_tab( $this->get_settings_subtab_slug() );

		// bail if tab does not exist.
		if ( ! $tab instanceof Tab ) {
			return;
		}

		// add section for file statistics.
		$section = $tab->get_section( 'section_' . $this->get_name() . '_main' );

		// bail if tab does not exist.
		if ( ! $section instanceof Section ) {
			return;
		}

		// add setting for region.
		if ( defined( 'EFML_ACTIVATION_RUNNING' ) || 'global' === get_option( 'eml_' . $this->get_name() . '_credentials_vault' ) ) {
			// add setting.
			$setting = $settings_obj->add_setting( 'eml_s3_access_key' );
			$setting->set_section( $section );
			$setting->set_autoload( false );
			$setting->set_type( 'string' );
			$setting->set_read_callback( array( $this, 'decrypt_value' ) );
			$setting->set_save_callback( array( $this, 'encrypt_value' ) );
			$field = new Text();
			$field->set_title( __( 'Access key', 'external-files-in-media-library' ) );
			/* translators: %1$s will be replaced by a URL. */
			$field->set_description( sprintf( __( 'Get your access key as described <a href="%1$s" target="_blank">here (opens in a new window)</a>.', 'external-files-in-media-library' ), 'https://docs.aws.amazon.com/solutions/latest/data-transfer-hub/set-up-credentials-for-amazon-s3.html' ) );
			$field->set_placeholder( __( 'The access key', 'external-files-in-media-library' ) );
			$setting->set_field( $field );

			// add setting.
			$setting = $settings_obj->add_setting( 'eml_s3_secret_key' );
			$setting->set_section( $section );
			$setting->set_autoload( false );
			$setting->set_type( 'string' );
			$setting->set_read_callback( array( $this, 'decrypt_value' ) );
			$setting->set_save_callback( array( $this, 'encrypt_value' ) );
			$field = new Password();
			$field->set_title( __( 'Secret key', 'external-files-in-media-library' ) );
			$field->set_placeholder( __( 'The secret key', 'external-files-in-media-library' ) );
			$setting->set_field( $field );

			// add setting.
			$setting = $settings_obj->add_setting( 'eml_s3_bucket' );
			$setting->set_section( $section );
			$setting->set_autoload( false );
			$setting->set_type( 'string' );
			$field = new Text();
			$field->set_title( __( 'Bucket', 'external-files-in-media-library' ) );
			$field->set_placeholder( __( 'The bucket you want to use.', 'external-files-in-media-library' ) );
			$setting->set_field( $field );
		}

		// show hint for user settings.
		if ( 'user' === get_option( 'eml_' . $this->get_name() . '_credentials_vault' ) ) {
			$setting = $settings_obj->add_setting( 'eml_s3_credential_location_hint' );
			$setting->set_section( $section );
			$setting->set_show_in_rest( false );
			$setting->prevent_export( true );
			$field = new TextInfo();
			$field->set_title( __( 'Hint', 'external-files-in-media-library' ) );
			/* translators: %1$s will be replaced by a URL. */
			$field->set_description( sprintf( __( 'Each user will find its settings in his own <a href="%1$s">user profile</a>.', 'external-files-in-media-library' ), $this->get_config_url() ) );
			$setting->set_field( $field );
		}

		// add setting.
		$setting = $settings_obj->add_setting( 'eml_s3_region' );
		$setting->set_section( $section );
		$setting->set_type( 'string' );
		$setting->set_default( $this->get_mapping_region() );
		$field = new Select();
		$field->set_title( __( 'Choose the region', 'external-files-in-media-library' ) );
		$field->set_options( $this->get_regions() );
		$setting->set_field( $field );

		// add setting to show also trashed files.
		$setting = $settings_obj->add_setting( 'eml_s3_import_limit' );
		$setting->set_section( $section );
		$setting->set_type( 'integer' );
		$setting->set_default( 10 );
		$field = new Number();
		$field->set_title( __( 'Max. files to load during import per iteration', 'external-files-in-media-library' ) );
		$field->set_description( __( 'This value specifies how many files should be loaded during a directory import. The higher the value, the greater the likelihood of timeouts during import.', 'external-files-in-media-library' ) );
		$field->set_setting( $setting );
		$field->set_readonly( $this->is_disabled() );
		$setting->set_field( $field );
	}

	/**
	 * Return list of AWS S3 regions for settings.
	 *
	 * @return array<string,string>
	 */
	private function get_regions(): array {
		// get cached value.
		$list = get_transient( 'eml_aws_s3_regions' );

		// use them if they are set.
		if ( ! empty( $list ) && is_array( $list ) ) {
			return $list;
		}

		// get all partitions from AWS S3 SDK.
		$partitions = EndpointDefinitionProvider::getPartitions();

		// bail if regions are not set there.
		if ( empty( $partitions['partitions'][0]['regions'] ) ) {
			return array();
		}

		// create our list for the settings.
		$list = array();
		foreach ( $partitions['partitions'][0]['regions'] as $name => $region ) {
			$list[ $name ] = $region['description'];
		}

		/**
		 * Filter the resulting list of AWS S3 regions.
		 *
		 * @since 5.0.0 Available since 5.0.0.
		 * @param array<string,string> $list List of regions.
		 */
		$list = apply_filters( 'efml_service_s3_regions', $list );

		// save the list in cache.
		set_transient( 'eml_aws_s3_regions', $list, WEEK_IN_SECONDS );

		// return the list.
		return $list;
	}

	/**
	 * Try to map the region according to the used WordPress language.
	 *
	 * @return string
	 */
	private function get_mapping_region(): string {
		// get actual language.
		$language = Languages::get_instance()->get_current_lang();

		// set the 'aws-global' as default slug for the region.
		$default_region = 'aws-global';

		// use eu-central-1 for german.
		if ( Languages::get_instance()->is_german_language() ) {
			return 'eu-central-1';
		}

		// return the 'eu-south-2' slug for spain.
		if ( 'es' === $language ) {
			return 'eu-south-2';
		}

		// return the 'ap-northeast-1' slug for japanese.
		if ( 'ja' === $language ) {
			return 'ap-northeast-1';
		}

		// return the 'il-central-1' slug for hebrew.
		if ( 'he' === $language ) {
			return 'il-central-1';
		}

		/**
		 * Filter the default AWS S3 region.
		 *
		 * @since 5.0.0 Available since 5.0.0.
		 * @param string $default_region The default region.
		 * @param string $language The actual language.
		 */
		return apply_filters( 'efml_service_s3_default_region', $default_region, $language );
	}

	/**
	 * Show option to connect to AWS S3 on the user profile.
	 *
	 * @param WP_User $user The WP_User object for the actual user.
	 *
	 * @return void
	 */
	public function add_user_settings( WP_User $user ): void {
		// bail if settings are not user-specific.
		if ( ! $this->is_mode( 'user' ) ) {
			return;
		}

		// bail if customization for this user is not allowed.
		if ( ! ImportDialog::get_instance()->is_customization_allowed() ) {
			return;
		}

		?><h3 id="efml-<?php echo esc_attr( $this->get_name() ); ?>"><?php echo esc_html__( 'AWS S3', 'external-files-in-media-library' ); ?></h3>
		<div class="efml-user-settings">
		<?php

		// show settings table.
		$this->get_user_settings_table( absint( $user->ID ) );

		?>
		</div>
		<?php
	}

	/**
	 * Return list of user settings.
	 *
	 * @return array<string,mixed>
	 */
	public function get_user_settings(): array {
		$list = array(
			's3_access_key' => array(
				'label'       => __( 'Access key', 'external-files-in-media-library' ),
				/* translators: %1$s will be replaced by a URL. */
				'description' => sprintf( __( 'Get your access key as described <a href="%1$s" target="_blank">here (opens in a new window)</a>.', 'external-files-in-media-library' ), 'https://docs.aws.amazon.com/solutions/latest/data-transfer-hub/set-up-credentials-for-amazon-s3.html' ),
				'field'       => 'text',
				'placeholder' => __( 'The access key', 'external-files-in-media-library' ),
			),
			's3_secret_key' => array(
				'label'       => __( 'Secret key', 'external-files-in-media-library' ),
				'field'       => 'password',
				'placeholder' => __( 'The secret key', 'external-files-in-media-library' ),
			),
			's3_bucket'     => array(
				'label'       => __( 'Bucket', 'external-files-in-media-library' ),
				'field'       => 'text',
				'placeholder' => __( 'The bucket you want to use', 'external-files-in-media-library' ),
			),
			's3_region'     => array(
				'label'   => __( 'Choose your region', 'external-files-in-media-library' ),
				'field'   => 'select',
				'options' => $this->get_regions(),
				'default' => $this->get_mapping_region(),
			),
		);

		/**
		 * Filter the list of possible user settings for AWS S3.
		 *
		 * @since 5.0.0 Available since 5.0.0.
		 * @param array<string,mixed> $list The list of settings.
		 */
		return apply_filters( 'efml_service_s3_user_settings', $list );
	}

	/**
	 * Return the URL mark, which identifies AWS S3 URLs within this plugin.
	 *
	 * @param string $bucket_name The bucket name.
	 *
	 * @return string
	 */
	public function get_url_mark( string $bucket_name ): string {
		return 'https://console.aws.amazon.com/s3/buckets/' . trailingslashit( $bucket_name );
	}

	/**
	 * Rebuild the resulting list to remove the pagination folders for clean view of the files.
	 *
	 * @param array<string,mixed> $listing The resulting list.
	 * @param string              $url The called URL.
	 * @param string              $service The used service.
	 *
	 * @return array<string,mixed>
	 * @noinspection PhpUnusedParameterInspection
	 */
	public function prepare_tree_building( array $listing, string $url, string $service ): array {
		// bail if this is not our service.
		if ( $this->get_name() !== $service ) {
			return $listing;
		}

		// move all directories in the tree.
		foreach ( $listing as $key => $value ) {
			// bail for the main entry.
			if ( $key === $url ) {
				continue;
			}

			// remove the used URL from key to get the directory hierarchy of this entry.
			$stripped_key = str_replace( trailingslashit( $url ), '', $key );

			// get the hierarchy.
			$parts = explode( '/', $stripped_key );

			// clean the URL.
			$cleaned_url = str_replace( $key, '', $url );

			// move the entry to the target entry in tree.
			foreach ( $parts as $part ) {
				// bail on empty part.
				if ( empty( $part ) ) {
					continue;
				}

				// create the index key.
				$index = $cleaned_url . trailingslashit( $part );

				// copy this to the main tree.
				$listing[ $url ]['dirs'][ $index ] = $value;
			}

			// remove the original entry.
			unset( $listing[ $key ] );
		}

		// if the main directory is not requested, search in the tree for the real target.
		if ( $this->directory !== $this->get_directory() ) {
			// search for the tree.
			$searched_tree = $this->get_real_tree( $listing, $this->directory );

			// return the complete tree if search directory none has been found.
			if ( empty( $searched_tree ) ) {
				return $listing;
			}

			// return the found tree.
			return $searched_tree;
		}

		// return the resulting tree.
		return $listing;
	}

	/**
	 * Return whether given file on bucket is public available.
	 *
	 * @param string   $file_key The file key.
	 * @param S3Client $s3 The S3 client object.
	 *
	 * @return bool
	 */
	public function is_file_public_available( string $file_key, S3Client $s3 ): bool {
		// get the permissions to check if file is public available.
		$public_access_allowed = false;
		$query                 = array(
			'Bucket' => $this->get_bucket_name(),
			'Key'    => $file_key,
		);
		$permissions           = $s3->getObjectAcl( $query );
		foreach ( $permissions->get( 'Grants' ) as $grant ) {
			// bail if URI is not set.
			if ( empty( $grant['Grantee']['URI'] ) ) {
				continue;
			}

			// bail if URI is not for all users.
			if ( 'http://acs.amazonaws.com/groups/global/AllUsers' !== $grant['Grantee']['URI'] ) {
				continue;
			}

			// bail if permission is not read or write.
			if ( ! in_array( $grant['Permission'], array( 'READ', 'WRITE' ), true ) ) {
				continue;
			}

			// file is public available.
			$public_access_allowed = true;
		}

		// if check was not successfully check with a short HTTP header request.
		if ( ! $public_access_allowed ) {
			// get the response.
			$response = wp_safe_remote_head( $this->get_public_url_of_file( $file_key ) );

			// if HTTP status is 200, its public.
			if ( 200 === wp_remote_retrieve_response_code( $response ) ) {
				$public_access_allowed = true;
			}
		}

		// return the result.
		return $public_access_allowed;
	}

	/**
	 * Remove the authorization header for requests on public AWS S3 files as their usage
	 * would result in HTTP status 400 from AWS S3.
	 *
	 * @param array<string,mixed> $args The arguments.
	 * @param Protocol_Base       $http The used protocol.
	 *
	 * @return array<string,mixed>
	 */
	public function remove_authorization_header( array $args, Protocol_Base $http ): array {
		// bail if URL on protocol is not ours.
		if ( ! str_contains( $http->get_url(), '.amazonaws.com' ) ) {
			return $args;
		}

		// remove the authorization header.
		unset( $args['headers']['Authorization'] );

		// remove resulting arguments.
		return $args;
	}

	/**
	 * Return list of fields we need for this listing.
	 *
	 * @return array<string,array<string,mixed>>
	 */
	public function get_fields(): array {
		// set fields, if they are empty atm.
		if ( empty( $this->fields ) ) {
			// get the prepared values for the fields.
			$values = $this->get_field_values();

			// set the fields.
			$this->fields = array(
				'access_key' => array(
					'name'        => 'access_key',
					'type'        => 'text',
					'label'       => __( 'Access key', 'external-files-in-media-library' ),
					'placeholder' => __( 'The access key', 'external-files-in-media-library' ),
					'credential'  => true,
					'value'       => $values['access_key'],
					'readonly'    => ! empty( $values['access_key'] ),
				),
				'secret'     => array(
					'name'        => 'secret',
					'type'        => 'password',
					'label'       => __( 'Secret key', 'external-files-in-media-library' ),
					'placeholder' => __( 'The secret key', 'external-files-in-media-library' ),
					'credential'  => true,
					'value'       => $values['secret_key'],
					'readonly'    => ! empty( $values['secret_key'] ),
				),
				'bucket'     => array(
					'name'        => 'bucket',
					'type'        => 'text',
					'label'       => __( 'Bucket', 'external-files-in-media-library' ),
					'placeholder' => __( 'The bucket you want to use', 'external-files-in-media-library' ),
					'value'       => $values['bucket'],
					'readonly'    => ! empty( $values['bucket'] ),
				),
				'region'     => array(
					'name'        => 'region',
					'type'        => 'select',
					'label'       => __( 'Region', 'external-files-in-media-library' ),
					'placeholder' => __( 'The region the bucket is located in', 'external-files-in-media-library' ),
					'options'     => $this->get_regions_for_react(),
					'value'       => $values['region'],
					'readonly'    => ! empty( $values['region'] ),
				),
			);
		}

		// return the list of fields.
		return parent::get_fields();
	}

	/**
	 * Return the bucket from fields.
	 *
	 * @return string
	 */
	public function get_bucket_name(): string {
		// get the fields.
		$fields = $this->get_fields();

		// return nothing if no bucket is set.
		if ( ! isset( $fields['bucket']['value'] ) ) {
			return '';
		}

		// return the bucket from fields.
		return $fields['bucket']['value'];
	}

	/**
	 * Return the form title.
	 *
	 * @return string
	 */
	public function get_form_title(): string {
		// bail if credentials are set.
		if ( $this->has_credentials_set() ) {
			return __( 'Connect to your AWS S3', 'external-files-in-media-library' );
		}

		// return default title.
		return __( 'Enter your credentials', 'external-files-in-media-library' );
	}

	/**
	 * Return the form description.
	 *
	 * @return string
	 */
	public function get_form_description(): string {
		// get the fields.
		$has_credentials_set = $this->has_credentials_set();

		// if access token is set in plugin settings.
		if ( $this->is_mode( 'global' ) ) {
			if ( $has_credentials_set && ! current_user_can( 'manage_options' ) ) {
				return __( 'An authentication JSON has already been set by an administrator in the plugin settings. Just connect for show the files.', 'external-files-in-media-library' );
			}

			if ( ! $has_credentials_set && ! current_user_can( 'manage_options' ) ) {
				return __( 'An authentication JSON must be set by an administrator in the plugin settings.', 'external-files-in-media-library' );
			}

			if ( ! $has_credentials_set ) {
				/* translators: %1$s will be replaced by a URL. */
				return sprintf( __( 'Set your authentication JSON <a href="%1$s">here</a>.', 'external-files-in-media-library' ), $this->get_config_url() );
			}

			/* translators: %1$s will be replaced by a URL. */
			return sprintf( __( 'Your access token is already set <a href="%1$s">here</a>. Just connect for show the files.', 'external-files-in-media-library' ), $this->get_config_url() );
		}

		// if authentication JSON is set per user.
		if ( $this->is_mode( 'user' ) ) {
			if ( ! $has_credentials_set ) {
				/* translators: %1$s will be replaced by a URL. */
				return sprintf( __( 'Set your authentication JSON <a href="%1$s">in your profile</a>.', 'external-files-in-media-library' ), $this->get_config_url() );
			}

			/* translators: %1$s will be replaced by a URL. */
			return sprintf( __( 'Your authentication JSON is already set <a href="%1$s">in your profile</a>. Just connect for show the files.', 'external-files-in-media-library' ), $this->get_config_url() );
		}

		/* translators: %1$s will be replaced by a URL. */
		return sprintf( __( 'Enter your AWS S3 credentials in this form. How to obtain them is described <a href="%1$s">here</a>.', 'external-files-in-media-library' ), 'https://docs.aws.amazon.com/solutions/latest/data-transfer-hub/set-up-credentials-for-amazon-s3.html' );
	}

	/**
	 * Return whether credentials are set in the fields.
	 *
	 * @return bool
	 */
	private function has_credentials_set(): bool {
		// get the fields.
		$fields = $this->get_fields();

		// return whether both credentials are set.
		return ! empty( $fields['access_key'] ) && ! empty( $fields['secret_key'] );
	}

	/**
	 * Change the query for files.
	 *
	 * @param array<string,mixed> $query The query.
	 *
	 * @return array<string,mixed>
	 */
	public function change_file_query( array $query ): array {
		// bail if directory is not set.
		if ( empty( $this->directory ) ) {
			return $query;
		}

		// get the requested directory.
		$directory = str_replace(
			array(
				$this->get_url_mark( $this->get_bucket_name() ),
				$this->get_directory(),
			),
			'',
			$this->directory
		);

		// bail if directory is empty.
		if ( empty( $directory ) ) {
			return $query;
		}

		// add the query for the directory.
		$query['Prefix']    = $directory;
		$query['Delimiter'] = '/';

		// return the resulting query.
		return $query;
	}

	/**
	 * Return the values depending on actual mode.
	 *
	 * @return array<string,mixed>
	 */
	private function get_field_values(): array {
		// prepare the return array.
		$values = array(
			'access_key' => '',
			'secret_key' => '',
			'bucket'     => '',
			'region'     => '',
		);

		// get it global, if this is enabled.
		if ( $this->is_mode( 'global' ) ) {
			$values['access_key'] = Crypt::get_instance()->decrypt( get_option( 'eml_s3_access_key', '' ) );
			$values['secret_key'] = Crypt::get_instance()->decrypt( get_option( 'eml_s3_secret_key', '' ) );
			$values['bucket']     = get_option( 'eml_s3_bucket', '' );
			$values['region']     = get_option( 'eml_s3_region', '' );
		}

		// save it user-specific, if this is enabled.
		if ( $this->is_mode( 'user' ) ) {
			// get the user set on object.
			$user = $this->get_user();

			// bail if user is not available.
			if ( ! $user instanceof WP_User ) {
				return array();
			}

			// get the values.
			$values['access_key'] = Crypt::get_instance()->decrypt( get_user_meta( $user->ID, 'efml_s3_access_key', true ) );
			$values['secret_key'] = Crypt::get_instance()->decrypt( get_user_meta( $user->ID, 'efml_s3_secret_key', true ) );
			$values['bucket']     = Crypt::get_instance()->decrypt( get_user_meta( $user->ID, 'efml_s3_bucket', true ) );
			$values['region']     = Crypt::get_instance()->decrypt( get_user_meta( $user->ID, 'efml_s3_region', true ) );
		}

		// return the resulting list of values.
		return $values;
	}

	/**
	 * Convert the region list to a react-compatible array.
	 *
	 * @return array<int,array<string,string>>
	 */
	private function get_regions_for_react(): array {
		// get the regions.
		$regions = $this->get_regions();

		// create list for react.
		$regions_for_react = array();

		// add each region to the list.
		foreach ( $regions as $key => $value ) {
			$regions_for_react[] = array(
				'value' => $key,
				'label' => $value,
			);
		}

		// return the resulting list.
		return $regions_for_react;
	}

	/**
	 * Return the export object for this service.
	 *
	 * @return Export_Base|false
	 */
	public function get_export_object(): Export_Base|false {
		return Export::get_instance();
	}

	/**
	 * Allow to use AWS S3 URLs which return "application/octed-stream" for files.
	 *
	 * @param bool   $return_value The return value (true to check the file type, so we return here false).
	 * @param string $url The URL to check.
	 *
	 * @return bool
	 */
	public function allow_content_type( bool $return_value, string $url ): bool {
		// bail if this is not an AWS S3 URL.
		if ( ! str_contains( $url, 'amazonaws.com' ) ) {
			return $return_value;
		}
		return false;
	}

	/**
	 * Set the real mime type for AWS S3 file URLs.
	 *
	 * @param array<string,mixed> $results The results.
	 * @param string              $url The used URL.
	 *
	 * @return array<string,mixed>
	 */
	public function set_real_mime_type( array $results, string $url ): array {
		// bail if this is not our file URL.
		if ( ! str_contains( $url, 'amazonaws.com' ) ) {
			return $results;
		}

		// get the mime type.
		$mime_type = wp_check_filetype( basename( $url ) );

		// set the mime type.
		$results['mime-type'] = $mime_type['type'];

		// return the resulting file data.
		return $results;
	}

	/**
	 * Return the public URL of a given key.
	 *
	 * @param string $key The key.
	 *
	 * @return string
	 */
	public function get_public_url_of_file( string $key ): string {
		return sprintf(
			'https://%s.s3.%s.amazonaws.com/%s',
			$this->get_bucket_name(),
			$this->get_region(),
			$key
		);
	}

	/**
	 * Return the real tree from given directory.
	 *
	 * @param array<string,mixed> $tree The tree.
	 * @param string              $directory The searched directory path.
	 *
	 * @return array<string,mixed>
	 */
	private function get_real_tree( array $tree, string $directory ): array {
		// create the return value.
		$real_tree = array();

		// loop through the tree.
		foreach ( $tree as $key => $value ) {
			// bail if directory has been found.
			if ( $key === $directory ) {
				return array( $key => $value );
			}

			// check the deeper tree entries.
			$real_tree = $this->get_real_tree( $value['dirs'], $directory );
		}

		// return the found directory.
		return $real_tree;
	}
}
