<?php
/**
 * Plugin Name:       External files in Media Library
 * Description:       Enables the Media Library to use external files.
 * Requires at least: 6.2
 * Requires PHP:      8.0
 * Version:           @@VersionNumber@@
 * Author:            Thomas Zwirner
 * Author URI:        https://www.thomaszwirner.de
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       external-files-in-media-library
 *
 * @package external-files-in-media-library
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// do nothing if PHP-version is not 8.0 or newer.
if ( version_compare( PHP_VERSION, '8.0', '<' ) ) {
	return;
}

use ExternalFilesInMediaLibrary\Plugin\Init;

// get plugin-path.
const EFML_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// include necessary file.
require_once __DIR__ . '/inc/constants.php';

// initialize plugin.
Init::get_instance()->init();
