<?php
/**
 * Tasks to run during uninstallation of this plugin.
 *
 * @package external-files-in-media-library
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	die;
}

use ExternalFilesInMediaLibrary\Plugin\Uninstall;

// get plugin-path.
const EFML_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// include necessary file.
require_once __DIR__ . '/inc/constants.php';

// run the uninstaller-methods.
Uninstall::get_instance()->run();
