<?php
/**
 * Tasks to run during uninstallation of this plugin.
 *
 * @package external-files-in-media-library
 */

// prevent direct access.
defined( 'ABSPATH' ) || exit;

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	die;
}

// do nothing if PHP-version is not 8.1 or newer.
if ( PHP_VERSION_ID < 80100 ) { // @phpstan-ignore if.alwaysFalse,smaller.alwaysFalse
	return;
}

use ExternalFilesInMediaLibrary\Plugin\Uninstall;

// get plugin-path.
const EFML_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// include necessary file.
require_once __DIR__ . '/inc/constants.php';

// run the uninstaller-methods.
Uninstall::get_instance()->run();
