name: Update Hook documentation

on:
  workflow_dispatch:

jobs:
  build:
    name: Update Hook documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run package installs and builds
        run: |
          composer install
          composer update

      - name: Generate hooks documentation file
        run: vendor/bin/wp-documentor parse app --format=markdown --output=docs/hooks.md --prefix=eml_ --exclude=Section.php --exclude=Tab.php --exclude=Import.php --exclude=Export.php --exclude=Field_Base.php --exclude=Settings.php --exclude=Page.php --exclude=Rest.php

      - name: Update file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update hook documentation
          branch: feature/updateHookDocumentation
          create_branch: true
          commit_options: '--no-verify --signoff'
          file_pattern: docs/hooks.md
